version: "3.8"
services:
  db:
    image: mongo
    container_name: book-nosql
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - 127.0.0.1:3900:27017
    restart: unless-stopped
